### YamlMime:FAQ
metadata:
  title: Perguntas frequentes sobre segurança
  description: Mantenha-se atualizado com perguntas e respostas de segurança frequentes sobre HoloLens de realidade misturada.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: b09670ee24139c129629d061edae4d5bb43b2d766c90df152aeddb202cc1fe55
  ms.sourcegitcommit: f8e7cc2fbdcdf8962700fd50b9c017bd83d1ad65
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 08/05/2021
  ms.locfileid: "115662655"
title: Perguntas Frequentes sobre Segurança do HoloLens (1ª geração)
summary: ''
sections:
- name: Ignored
  questions:
  - question: >
      Qual nível de proteção de dados HoloLens 1 oferece?
    answer: >
      * Consulte [HoloLens criptografia do BitLocker (1ª geração)](hololens1-encryption.md)
  - question: >
      Que tipo de sem fio é usado?
    answer: >
      * 802.11ac e Bluetooth 4.1 LE
  - question: >
      Que tipo de arquitetura é incorporada?  Por exemplo: ponto a ponto, malha ou outra coisa?
    answer: >
      * Wi-Fi pode ser usado no modo de infraestrutura para se comunicar com outros pontos de acesso sem fio.

      * Bluetooth pode ser usado para conversar ponto a ponto entre vários HoloLens se o aplicativo dos clientes dá suporte a ele ou a outros Bluetooth dispositivos.
  - question: >
      O que é a ID DE LTDA?
    answer: >
      * C3K1688
  - question: >
      Em que intervalo de frequência e canais o dispositivo opera e ele é configurável?
    answer: >
      * Wi-Fi: o intervalo de frequência não é configurável pelo usuário e depende do país de uso. No Wi-Fi usa canais de 2,4 GHz (1 a 11) e 5 GHz (36-64, 100-165).

      * Bluetooth: Bluetooth usa o intervalo padrão de 2,4 a 2,48 GHz.
  - question: >
      O dispositivo pode permitir ou bloquear frequências específicas?
    answer: >
      * Isso não é controlável pelo usuário/dispositivo.
  - question: >
      Qual é o nível de energia para transmissão e recebimento? É ajustável? Qual é o intervalo de operação?
    answer: >
      * Nossos padrões de teste de emissões podem ser [encontrados aqui.](https://fccid.io/C3K1688) O intervalo de operação é altamente dependente do ponto de acesso e do ambiente , mas é aproximadamente equivalente a outros telefones, tablets ou computadores de alta qualidade.
  - question: >
      Qual é o ciclo de trabalho/tempo de vida para a operação normal?
    answer: >
      * 2 a 3 horas de uso ativo e até duas semanas de tempo de espera

      * O tempo de vida da bateria não está disponível.
  - question: >
      O que é o comportamento de transmissão e recebimento quando uma ferramenta não está no intervalo?
    answer: >
      * HoloLens transmissão/recebimento segue o padrão Wi-Fi/Bluetooth padrão. Na borda de seu intervalo, você provavelmente observará a entrada ficando insaluporta até que ela seja totalmente desconectada, mas depois de voltar ao intervalo, ela deverá se reconectar rapidamente.
  - question: >
      O que é a densidade de implantação por pé quadrado?
    answer: >
      * Isso depende da infraestrutura de rede.
  - question: >
      O dispositivo pode usar a infraestrutura como um cliente?
    answer: >
      * Yes
  - question: >
      Qual protocolo é usado?
    answer: >
      * HoloLens não usa nenhum protocolo proprietário
  - question: >
      Frequência de atualização do sistema operacional – qual é a frequência de atualizações do sistema operacional para o HL?  Há um agendamento definido?  A Microsoft libera patches de segurança conforme necessário, etc.
    answer: >
      * A Microsoft fornece atualizações do sistema operacional HoloLens exatamente da mesma maneira que é feito para Windows 10. Normalmente, há duas atualizações principais por ano, uma na spring e outra no fall. Como HoloLens é um Windows, o conceito de atualização é o mesmo que com qualquer outro Windows dispositivo. A Microsoft libera patches de segurança conforme necessário e segue o mesmo conceito que feito em qualquer outro Windows dispositivo.
  - question: >
      Proteger o sistema operacional – Quais opções existem para proteger o sistema operacional?  Podemos remover ou desligar aplicativos ou serviços desnecessários?
    answer: >
      * HoloLens se comporta como um smartphone. Ele é comparável a outros dispositivos Windows modernos. HoloLens pode ser gerenciado por Microsoft Intune ou por outras soluções de Gerenciamento de Dispositivos modernas, como MobileIron, Airwatch ou Soti. Há políticas que você pode definir nesses Sistemas de Gerenciamento para colocar políticas de segurança no dispositivo e para proteger o dispositivo. Também há a opção de excluir todos os aplicativos desnecessários, se quiser.
  - question: >
      Como os aplicativos de software serão gerenciados e atualizados? Qual controle temos para definir quais aplicativos são carregados e o processo de atualização de aplicativos para aplicativos que estão morando na Microsoft Store?
    answer: >
      * HoloLens obtém aplicativos de software somente por meio do Windows store. Somente os Pacotes de Aplicativos Appx podem ser instalados, que são desenvolvidos para o uso de HoloLens. Você pode ver isso no Microsoft Store com um pequeno logotipo ao lado do aplicativo que mostra o HoloLens dispositivo. Qualquer controle que você tenha sobre o gerenciamento de aplicativos da Store também se aplica HoloLens. Você pode usar o conceito da loja oficial ou da loja para empresas. Os aplicativos podem ser carregados lado a lado (processo manual para carregar um aplicativo em um dispositivo Windows) ou podem ser gerenciados por meio de um MDM para que os aplicativos sejam retirados automaticamente da loja quando necessário.
  - question: >
      Qual é a frequência de atualizações para aplicativos na loja para HoloLens?
    answer: >
      * Como seguimos o mesmo conceito de aplicativos Microsoft Store pull de lá, o ciclo de atualização é determinado pelo desenvolvedor do Aplicativo. Todas as opções de gerenciamento que você precisa para controlar o mecanismo de atualização no armazenamento se aplicam HoloLens também.
  - question: >
      Há uma funcionalidade de inicialização segura para o HoloLens?
    answer: >
      * Yes
  - question: >
      Há uma capacidade de desabilitar ou desconectar o suporte periférico do dispositivo?
    answer: >
      * Yes
  - question: >
      Há uma capacidade de controlar ou desabilitar o uso de portas no dispositivo?
    answer: >
      * O HoloLens contém apenas duas portas (uma para fones de ouvido e outra para carregar ou conectar-se a PCs). Não há capacidade de desabilitar a porta devido a motivos de funcionalidade e recuperação.
  - question: >
      Antivírus, detecção de ponto de extremidade, IPS, lista de permitir controle de aplicativo – qualquer capacidade de executar antivírus, detecção de ponto de extremidade, IPS, lista de permitir controle de aplicativo etc.
    answer: >
      * Windows Holographic for Business (pacote comercial) dá suporte Windows Defender Smart Screen. Se uma empresa antivírus criar e publicar seu aplicativo na Plataforma Universal do Windows, ele poderá ser baixado no HoloLens. No momento, nenhuma empresa fez isso por HoloLens.

      * Permitir aplicativos é possível usando a Microsoft Enterprise Store, na qual você pode escolher apenas quais aplicativos específicos podem ser baixados. Além disso, por meio do MDM, você pode bloquear quais aplicativos específicos podem ser executados ou até mesmo vistos no dispositivo.
  - question: >
      Podemos colocar o dispositivo em quarentena da rede prod até atualizarmos o dispositivo se ele estiver offline por um longo período de tempo?  Ex.: O dispositivo está em uma gaveta não ligado por um período (seis meses) e não recebeu atualizações, patches etc.  Quando ele tenta entrar na rede, podemos sinalizá-la e dizer que você deve atualizar em outra rede antes de ser reclamações para ingressar na rede.
    answer: >
      * Isso é algo que pode ser gerenciado no nível da infraestrutura por um MDM ou um servidor local. O dispositivo poderá ser sinalizado como não compatível se não atender a uma versão de Atualização especificada.
  - question: >
      A Microsoft inclui portas traseiras ou acesso a serviços que permitem que a Microsoft se conecte ao dispositivo para compartilhamento de tela ou suporte remoto à vontade?
    answer: >
      * No
  - question: >
      Quando um certificado PKI está sendo gerado para comunicação confiável, queremos que o certificado seja gerado no dispositivo para que saibamos que ele está apenas nesse dispositivo, exclusivo para esse dispositivo e não pode ser exportado ou usado para representar o dispositivo. Isso é verdadeiro no HoloLens? Caso não haja uma possível mitigação?
    answer: >-
      * O CSR para SCEP é gerado no próprio dispositivo. O Intune e o conector SCEP local ajudam a proteger as próprias solicitações adicionando e verificando uma cadeia de caracteres de desafio enviada ao cliente.

      * Como HoloLens (1ª geração e 2ª geração) têm um módulo TPM, esses certificados seriam armazenados no módulo TPM e não podem ser extraídos. Além disso, mesmo que ela possa ser extraída, as cadeias de caracteres de desafio não puderam ser verificadas em um dispositivo diferente, tornando os certificados/chave inutilizáveis em dispositivos diferentes.
